// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recipe_tracker.Database.Repositories;

#nullable disable

namespace recipe_tracker.Migrations
{
    [DbContext(typeof(RecipeTrackerContext))]
    [Migration("20251001171926_addIngredients")]
    partial class addIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("recipe_tracker.Database.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeID")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Instruction", b =>
                {
                    b.Property<int>("InstructionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstructionID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeDetailsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeID");

                    b.HasIndex("RecipeDetailsID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.RecipeDetails", b =>
                {
                    b.Property<int>("RecipeDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CookMins")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepMins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeDetailsID");

                    b.ToTable("RecipeDetails");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Ingredient", b =>
                {
                    b.HasOne("recipe_tracker.Database.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeID");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Instruction", b =>
                {
                    b.HasOne("recipe_tracker.Database.Models.Recipe", null)
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeID");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Recipe", b =>
                {
                    b.HasOne("recipe_tracker.Database.Models.RecipeDetails", "RecipeDetails")
                        .WithMany()
                        .HasForeignKey("RecipeDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("recipe_tracker.Database.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
